#ifndef __VECTOR_SUB_SERVICE_COMMAND_H__
#define __VECTOR_SUB_SERVICE_COMMAND_H__

enum vector_sub_service_command
{
    VECTOR_SUB_SERVICE_EXECUTE,
    VECTOR_SUB_SERVICE_END
};

#define VECTOR_SUB_SERVICE_EXECUTE_BUFFER_COUNT         (VECTOR_SUB_SERVICE_END)
#define VECTOR_SUB_SERVICE_EXECUTE_BUFFER               ((VECTOR_SUB_SERVICE_END) - 1)

#endif
